### ISSUE TITLE
fastqc-rs is much slower than Falco (a C++ version of fastqc)

### ISSUE THREAD

**Issue by jianshu93** [fxwiegand/fastqc-rs#5]
Dear fastqc-rs team,

I ran a test using both falco and fastqc-rs but found fastqc-rs is much slower compare to falco (https://github.com/smithlabcode/falco): 40 million reads falco takes only 1.5 minutes while fastqc-rs takes 22 minutes. I think the needle tail library for reading fastq file is much faster than any other C/C++ library? Any idea to improve?

Many thanks,

Jianshu

**Comment by jianshu93** [comment]
Or it has something to do with the Khmer counting? kmerutils (https://github.com/jean-pierreBoth/kmerutils) library are extremely fast and memory efficient for kmer counting. 

Thanks,

Jianshu

**Comment by fxwiegand** [comment]
I'd assume it's the kmer counting like you already suggested. I am using rusts internal `HashMap` with kmers represented by u8 slices to count them which is probably not optimal but gives the option to easily specify different values for k. I am not sure if `falco` is even counting all kmers. At least they aren't shown in the report if i am correct. I just did some tests with smaller fastq files and found that on average `falco` was about 3 times faster than `fastqc-rs`. I am wondering whether this is due to the smaller file size or some other factors. Did you install both using conda for your tests?

**Comment by jianshu93** [comment]
No I compiled both from source.

Why kmer counting takes so long? Any idea to accelerate.

Thanks,

Jianshu

**Comment by fxwiegand** [comment]
So you compiled with `cargo build` and then tested with `cargo run` i assume?

**Comment by jianshu93** [comment]
Yes cargo build and then use the binary in the release directory (cargo build --release)

Jianshu

**Comment by fxwiegand** [comment]
Ah ok so you didn't use `cargo run`? Because this would have meant there was quite a lot less optimization. Would you mind sharing or pointing me to the fastq file you used for testing? I'd like to see if i also get that big of difference on my machine.

**Comment by fxwiegand** [comment]
I was looking through the forks - didn't even notice there were some until some days ago - and saw that @nlhelper has implemented some speedups. I'd be happy to have a PR for these.

**Comment by fxwiegand** [comment]
As i had a look at the forks - didn't know that there were some until a few days ago - i noticed that @nlhepler has implemented some speedups. I'd be very happy to merge those if he agrees.

**Comment by jianshu93** [comment]
Hi All, any possibility to also make it parallel, like processing reads using multiple threads to be faster? I was under the impression that the algorithm is easily parallelized using rayon.

Thanks,

Jianshu

**Comment by fxwiegand** [comment]
I am not so sure about that but feel free to give it a shot and do some benchmarking! I'd be happy to merge any PR with performance improvements!
